services:
  devops-ltc-mongodb:
    image: mongo:4.4
    container_name: devops-ltc-mongodb
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - devops-ltc-mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: always

  devops-ltc-service:
    image: node:22-alpine
    container_name: devops-ltc-service
    working_dir: /workspace
    command: sh -lc "corepack enable && npm start"
    environment:
      HOSTNAME: 0.0.0.0
      CHOKIDAR_USE_POLLING: "true"
      WATCH PACK_POLLING: "true"
      PORT: 3000
      MONGO_URI: mongodb://devops-ltc-mongodb:27017/products_db
    volumes:
      - .:/workspace
      - ./public/uploads:/workspace/public/uploads
    ports:
      - "3000:3000"
    depends_on:
      devops-ltc-mongodb:
        condition: service_healthy
    restart: always

volumes:
  devops-ltc-mongodb: